//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> BookQuantity { get; set; }
    
        public virtual tbl_books tbl_books { get; set; }
        public virtual tbl_orders tbl_orders { get; set; }
    }
}
